schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"

  types:
    EnvironmentInput:
      type: object
      description: "Input properties for eks environment."
      properties:
        kubernetes_version:
          type: string
          description: "K8s version"
          default: "1.21"
        tenant:
          type: string
          description: "Name for tenant"
          default: aws001
        environment:
          type: string
          description: "Name for environment"
          default: "dev"
        zone:
          type: string
          description: "Name for zone"
          default: "preprod"
